# .github/workflows/test-simple.yml
name: Test Simple Django Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Cho phép chạy manual

jobs:
  test-simple:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Print debug info
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"
        echo "Event: ${{ github.event_name }}"
    
    - name: List files
      run: ls -la
    
    - name: Test Python installation
      run: |
        python --version
        pip --version
    
    - name: Hello World
      run: echo "GitHub Actions is working! 🎉"